server:
  port: 8082

spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  mvc:
    async:
      request-timeout: -1
  cloud:
    azure:
      servicebus:
        namespace: theanh2906
        entity-name: benna
        entity-type: queue
      storage:
        queue:
          account-name: benna
          queue-name: benna-queue
          credential:
            managed-identity-enabled: true
        blob:
          account-name: benna
          account-key: GNjwKgTb919QBC8oN84mOgSUsUXCQwR61KhCnpMrDom7aAg4fpzqkQakeJuGDN9nr0XU7zRS5iYA+ASthMRkMA==
          endpoint: https://benna.blob.core.windows.net
      appconfiguration:
        credential:
          managed-identity-enabled: true
          client-id: 668a0ff9-708d-4fee-86f2-5dac235f0c1b


r2dbc:
  db:
    connection:
      minimum:
        idle: 1

fshare:
  app-key: dMnqMMZMUnN5YpvKENaEhdQQ5jxDqddt
  user-agent: UsefulTools2022-710L5E
  email: theanh2906@gmail.com
  password: Jackytang2906*
