server:
  port: 8082

spring:
  data:
    postgres:
      host: localhost
      port: 5432
      database: postgres
      username: postgres
      password: Jackytang2906

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Jackytang2906
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  mvc:
    async:
      request-timeout: -1

r2dbc:
  db:
    connection:
      minimum:
        idle: 1

fshare:
  app-key: dMnqMMZMUnN5YpvKENaEhdQQ5jxDqddt
  user-agent: UsefulTools2022-710L5E
  email: theanh2906@gmail.com
  password: Jackytang2906*
