server:
  port: 8082

spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  mvc:
    async:
      request-timeout: -1
  cloud:
    azure:
      storage:
        queue:
          account-name: benna
          queue-name: benna-queue

r2dbc:
  db:
    connection:
      minimum:
        idle: 1

fshare:
  app-key: dMnqMMZMUnN5YpvKENaEhdQQ5jxDqddt
  user-agent: UsefulTools2022-710L5E
  email: theanh2906@gmail.com
  password: Jackytang2906*
